# AI Service Configuration

server:
  host: "0.0.0.0"
  port: 8000
  debug: true

model:
  style_transfer:
    num_reference_images: 1
    content_weight: 1.0
    style_weight: 1.0
    batch_size: 1

  feature_extraction:
    model_name: "vgg19"
    layers:
      - "conv1_1"
      - "conv2_1"
      - "conv3_1"
      - "conv4_1"
      - "conv5_1"

paths:
  period_mapped_data: "../data_processing/data/period-mapped/period_mapped_data.json"
  model_weights: "./models/weights"
  temp_storage: "./temp"

processing:
  max_image_size: 1024
  output_size: 800
  jpeg_quality: 90

# Tuning parameters for Style Transfer
tuning:
  # Weight for matching the content image structure.
  # Higher values prioritize preserving the original photo's shapes and objects.
  # Typical range relative to style_weight. If style_weight is 1e6, content might be 1 to 100.
  content_weight: 1.0

  # Weight for matching the style image texture/patterns.
  # Higher values make the output look more like the style image.
  # Often significantly higher than content_weight (e.g., 1e4 to 1e7). Too high can destroy content.
  style_weight: 1000000.0 # Example: 1e6

  # Weight for image smoothness regularization (Total Variation Loss).
  # Higher values create smoother, more "painted" results, reducing noise but also detail.
  # Usually small (e.g., 1e-6 to 1e-4). Too high causes blurriness.
  tv_weight: 0.000001 # Example: 1e-6

  # Number of optimization iterations.
  # More steps allow finer adjustments towards the target loss, but take longer.
  # Typical range: 100-500. Fewer steps = faster, closer to content image.
  num_steps: 300

  # Learning rate for the Adam optimizer.
  # Smaller values (e.g., 0.001-0.01) are more stable but converge slower.
  # Larger values (e.g., 0.02-0.1) converge faster but risk instability/overshooting.
  learning_rate: 0.02

  # VGG19 layers used for content loss.
  content_layers: [conv4_2]

  # VGG19 layers used for style loss.
  style_layers: [conv1_1, conv2_1, conv3_1, conv4_1, conv5_1]

# Cloud service settings (Optional)
cloud_service:
  gradio_space_id: "Hexii/Neural-Style-Transfer"
  tfhub_magenta_model_url: "https://tfhub.dev/google/magenta/arbitrary-image-stylization-v1-256/2"

cache:
  enabled: true
  max_size: 100
  expiry_minutes: 60

post_processing:
  unsharp_mask:
    enabled: true
    amount: 1.0       # Sharpening amount (e.g., 0.5 to 2.0)
    sigma: 1.0        # Gaussian blur sigma (e.g., 0.5 to 2.0)
    threshold: 0      # Threshold for sharpening (0-255)

  clahe_contrast: # Contrast Limited Adaptive Histogram Equalization
    enabled: false
    clip_limit: 3.0   # Contrast limit (e.g., 1.0 to 5.0)
    tile_grid_size: 8 # Size of grid for histogram equalization (e.g., 8 for 8x8 tiles)

  saturation_boost:
    enabled: false
    factor: 3       # Saturation factor (1.0 = no change, >1.0 increases, <1.0 decreases)
